azooKey/azooKey

- .github/ISSUE_TEMPLATE/bug-report--不具合の報告-.md
Fixed a typo in ISSUE_TEMPLATE.
ISSUE_TEMPLATEのtypoを修正しました。
> Fix typo in ISSUE_TEMPLATE

- MainApp/Tips/Articles/KeyboardBehaviorIssueAfterInstallTipsView.swift
- MainApp/Tips/Articles/UseMarkedTextTipsView.swift
- MainApp/Tips/TipsView.swift
- Shared/en.lproj/Localizable.strings
- azooKey.xcodeproj/project.pbxproj
不具合報告が多く寄せられていた項目について、「困ったときは」を追加
Fix #14 
Fix #18
> [Usage Document] 不具合報告を受けていた項目について「困ったときは」を追加

- Keyboard/Converter/DicdataStore/DicdataStore.swift
- azooKey.xcodeproj/project.pbxproj
- azooKeyTests/KeyboardTests/ComposingTextTests.swift
- azooKeyTests/KeyboardTests/ConverterTests/ConverterTests.swift
- azooKeyTests/KeyboardTests/DicdataStoreTests/DicdataStoreTests.swift
本来charIDのdepthを渡すべき箇所で、inputDataのdepthを渡していたのが原因だった。
* バグを修正
* テストケースを追加
した。
> [Bug] ローマ字入力で「使った」などの変換がうまくいかない問題を修正

- MainApp/UpdateInformationView.swift
- azooKey.xcodeproj/project.pbxproj
Version 2.0.2のRCです。
審査を通過したらマージします。
> Update to version 2.0.2 RC

- azooKeyTests/KeyboardTests/DicdataStoreTests/DicdataStoreTests.swift
デグレ防止のため、「絶対に存在するべき」エントリのテストを用意した。
> [Test] 辞書エントリに関するテストを追加

- MainApp/UpdateInformationView.swift
- azooKey.xcodeproj/project.pbxproj
> Version 2.0.3 RC

- MainApp/MainApp.swift
- MainApp/Setting/OpenSourceSoftwaresLicenseView.swift
- MainApp/Setting/SettingTab.swift
- MainApp/Tips/Articles/FullAccessTipsView.swift
- Shared/en.lproj/Localizable.strings
- azooKey.xcodeproj/project.pbxproj
> [Design] 設定タブの順番の見直し

- MainApp/Customize/EditingTenkeyCustardView.swift
- Shared/KeyboardView/Tab.swift
- Shared/KeyboardView/View/KeyboardView.swift
> [Bug] カスタムタブのプレビューが更新されない不具合を修正

- Shared/KeyboardView/TabManager.swift
* 「前回のタブ」が存在しない場合、デフォルトのタブに移動するように変更した。
* メインの言語が英語の場合に英語タブが最初に表示されるように変更した。
> [Bug] last_tabへの移動の不具合を修正

- MainApp/ContentView.swift
- MainApp/Customize/CodableActionDataEditor.swift
- Shared/Custard/TabBarData.swift
- Shared/KeyboardView/TabManager.swift
- Shared/KeyboardView/View/CustomKeybaord/SimpleKeyView/SimpleKeyModel.swift
- Shared/KeyboardView/View/CustomKeybaord/SimpleKeyView/SimpleKeyView.swift
- Shared/KeyboardView/View/SpecialTabs/ClipboardHistoryTab.swift
- Shared/KeyboardView/View/SpecialTabs/EmojiTab.swift
- Shared/Message.swift
- Shared/SwiftUI/TouchDownAndTouchUpGesture.swift
resolve #100 
関連して、`azooKey://`のスキームを開いた際にURLの読み込みが走る不具合を修正した。
> [Feature] 絵文字タブを自動的に追加するよう変更

- Keyboard/Display/InputManager.swift
- Keyboard/Display/KeyboardActionManager.swift
- Shared/KeyboardView/Action.swift
- Shared/KeyboardView/VariableStates.swift
- Shared/KeyboardView/View/KeyboardBar/ResultBar.swift
> [Feature] smartDeleteなどの後に、タブバーボタンの右側に「取り消す」を表示するように変更

- Shared/ThemeData/ThemeManager.swift
- Shared/ThemeData/ThemePicture.swift
> [Performance] 着せ替え画像をmappedIfSafeで読み込むように変更

- Keyboard/Display/InputManager.swift
* 選択状態で空白を入力した場合の不具合を修正
* 実装を整えた
> [Fix] inputの実装を改善

- Keyboard/Converter/ComposingText.swift
- Keyboard/Converter/Converter/Converter.swift
- Keyboard/Display/InputManager.swift
- Keyboard/Display/LiveConversionManager.swift
> [Fix] ローマ字入力で1字を入力した場合に生じる不具合を修正

- azooKeyTests/KeyboardTests/DicdataStoreTests/DicdataStoreTests.swift
> [Test] 「何時」が変換できない問題に対しテストを追加

- Shared/KeyboardView/View/KeyboardBar/ResultBar.swift
> [BUG] bug that tab bar is not shown when user longpress empty result bar

- README.md
> Clarify how to contribute

- .gitignore
> [Refactoring] Add .DS_Store into .gitignore

- Keyboard/Converter/Converter/CalendarCandidate.swift
- Keyboard/Converter/Converter/VersionCandidate.swift
- azooKey.xcodeproj/project.pbxproj
#182 がなぜかclosedになってしまったので再度開いた
> [Refactoring] `Wareki.swift`をrenameし、`toVersionCandidate`を別のファイルに切り出した

- azooKey.xcodeproj/project.pbxproj
https://qiita.com/kaityo256/items/a822fc462a4de6ddd8e7 などを参照しLink Time Optimizationを試してみた。結果としてあまり効果はないが、Release時にオンにして悪いこともなさそうなので、有効化だけした。
Resolved #193
> [Performance] Enable Link Time Optimization (LTO)

- .github/workflows/swift.yml
> [CI] Add swift.yml for CI

- .gitignore
- README.md
- setup.sh
#201 で`gdown`を使ってgoogle driveのファイルを自動ダウンロードできることがわかったので、環境構築用のshを用意してみた。開発がかなり容易になる。
> [Refactoring] setupスクリプトを追加

- azooKey.xcodeproj/project.pbxproj
- azooKey.xcodeproj/xcshareddata/xcschemes/Keyboard.xcscheme
- azooKey.xcodeproj/xcshareddata/xcschemes/MainApp.xcscheme
- azooKey.xcodeproj/xcshareddata/xcschemes/azooKeyTests.xcscheme
> [Meta] Update for recommended setting in Xcode 14.3

- AzooKeyCore/Sources/KeyboardViews/VariableStates.swift
> [fix] enterKeyStateの更新漏れを修正

- azooKeyTests/KeyboardTests/ConverterTests/ConverterTests.swift
* Strict Concurrencyを有効にした結果ビルドが通らなくなっていたテストを修正
> [Fix] Fix build error due to concurrency checking

- MainApp/UpdateInformationView.swift
- azooKey.xcodeproj/project.pbxproj
* Version 2.1.1→Version 2.1.2
* 更新情報のテキストを追加
> [Feature] バージョン情報を更新

- AzooKeyCore/Sources/AzooKeyUtils/KeyboardSetting/AutoCompletionStrengthSetting.swift
- AzooKeyCore/Sources/AzooKeyUtils/KeyboardSetting/KeyboardSetting.swift
- AzooKeyCore/Sources/AzooKeyUtils/KeyboardSetting/MarkedTextSetting.swift
- AzooKeyCore/Sources/AzooKeyUtils/KeyboardSetting/QwertyCustomKeyKeyboardSetting.swift
- AzooKeyCore/Sources/KeyboardViews/Design.swift
- AzooKeyCore/Sources/KeyboardViews/View/Components/ResizingRect.swift
- AzooKeyCore/Sources/KeyboardViews/View/CustomKeybaord/CustomKeyboard.swift
- AzooKeyCore/Sources/KeyboardViews/View/FlickKeyboard/KeyView/FlickKeyModelProtocol.swift
- AzooKeyCore/Sources/KeyboardViews/View/FlickKeyboard/SuggestView/FlickedKeyModel.swift
- AzooKeyCore/Sources/KeyboardViews/View/KeyboardBar/EmojiTabResultBar.swift
- AzooKeyCore/Sources/KeyboardViews/View/KeyboardBar/ResultBar.swift
- AzooKeyCore/Sources/SwiftUIUtils/TouchDownAndTouchUpGesture.swift
- Keyboard/Display/KeyboardViewController.swift
- MainApp/Customize/CustardInformationView.swift
- MainApp/Customize/EditingTenkeyCustardView.swift
- MainApp/Customize/ManageCustardView.swift
- MainApp/General/CancelableEditor.swift
- MainApp/General/DraggableView.swift
- MainApp/General/Focus.swift
- MainApp/LOUDSLogic/LOUDSBuilder.swift
- MainApp/Setting/AdditionalDict/AzooKeyUserDictionary.swift
- MainApp/Setting/CustomKeys/FlickCustomKeys/FlickCustomKeySettingView.swift
- MainApp/Setting/CustomKeys/QwertyCustomKeys/QwertyCustomKeysItemView.swift
- MainApp/Setting/FlickSensitivitySetting/FlickSensitivitySettingView.swift
- MainApp/Setting/OpenSourceSoftwaresLicenseView.swift
- MainApp/Setting/Template/TemplateListView.swift
* Concurrency関連のWarningを複数修正
* Swiftlintの適用
> [Fix] Fixed warnings mainly relating to concurrency

- Keyboard/Display/InputManager.swift
> [Feature] 再変換時の予測変換をオフ

- MainApp/Customize/ManageCustardView.swift
- MainApp/General/FallbackLink.swift
- MainApp/Setting/AdditionalDict/AzooKeyUserDictionary.swift
- MainApp/Setting/BooleanSetting/BoolSettingView.swift
- MainApp/Setting/FlickSensitivitySetting/FlickSensitivitySettingView.swift
- MainApp/Setting/FontSizeSetting/FontSizeSettingItemView.swift
- MainApp/Setting/KeyboardHeightSetting/KeyboardHeightSettingView.swift
- MainApp/Setting/MarkedTextSetting/MarkedTextSettingView.swift
- MainApp/Setting/MemoryResetSetting/MemoryResetSetting.swift
> [Refactoring] Remove Alert.init

- AzooKeyCore/Sources/KeyboardViews/View/QwertyKeyboard/KeyView/QwertyKeyModelProtocol.swift
- AzooKeyCore/Sources/KeyboardViews/View/QwertyKeyboard/KeyView/QwertyKeyView.swift
#251 に向けて、まずDoublePressActionsのAPIを追加した。
また、関連する問題として連打によって打ち漏れが発生する不具合に対処した（Fix #253 ）
* CustardKitのAPIに二回押しアクションを追加する
> [Feature] 二回押しアクションをQwertyKeyViewで処理可能にした。

- DictionaryDebugger/KanaKanjiConvertResultViewer.swift
DictionaryDebuggerが並行性関連のエラーでビルドできなくなっていたのを修正した。
> [Fix] fix concurrency build error

- AzooKeyCore/Sources/KeyboardViews/View/FlickKeyboard/FlickKeyboardView.swift
> [Refactoring] FlickKeyboardViewの実装をCustardFlickKeysViewで置き換え

- Keyboard/Display/InputManager.swift
- Keyboard/Display/KeyboardActionManager.swift
> [Bug] crash when execute enter with cursor movement

- AzooKeyCore/Sources/KeyboardViews/View/KeyboardBar/ResultBar.swift
- AzooKeyCore/Sources/KeyboardViews/View/KeyboardBar/ResultViewItemData.swift
- Keyboard/Display/DisplayedTextManager.swift
- Keyboard/Display/InputManager.swift
- Keyboard/Display/KeyboardActionManager.swift
- Keyboard/Display/KeyboardViewController.swift
- Keyboard/Display/PredictionManager.swift
- azooKey.xcodeproj/project.pbxproj
#265 の前提として、prediction candidateを表示するためのUIを実装した。
適切に予測変換候補を返すエンジンを実装することで、予測変換ができる。
> [Feature] ゼロクエリの予測変換候補を表示するためのUIを実装

- AzooKeyCore/Package.swift
> [Refactoring] Update AzooKeyCore Swift version

- MainApp/Tips/Articles/iOS15TerminationNews.swift
- MainApp/Tips/TipsView.swift
- MainApp/UpdateInformationView.swift
- Resources/en.lproj/Localizable.strings
- azooKey.xcodeproj/project.pbxproj
> [Feature] iOS 15のサポート終了を予告するViewを追加

- MainApp/ContentView.swift
- MainApp/EnableAzooKeyView/EnableAzooKeyView.swift
- MainApp/MainApp.swift
> [Bug] tutorialの途中でフルアクセスの設定を変更した場合に「最初の設定」が表示されない問題を修正

- AzooKeyCore/Sources/KeyboardViews/VariableStates.swift
- Keyboard/Display/InputManager.swift
- Keyboard/Display/KeyboardActionManager.swift
> [feature] 検索フィールドなどで再変換を抑制

- MainApp/Customize/CodableActionDataEditor.swift
- Resources/Localizable.xcstrings
> [Feature] `smart_move_cursor`と`smart_delete`の編集機能を追加

- AzooKeyCore/Sources/KeyboardViews/View/CustomKeybaord/CustomKeyboard.swift
- MainApp/Customize/CustardInterfaceKeyEditor.swift
- Resources/Localizable.xcstrings
- azooKey.xcodeproj/project.pbxproj
Resolve #298 
Relating to https://github.com/ensan-hcl/CustardKit/pull/53
> [Feature] Support upper/lower key

- Keyboard/Display/KeyboardActionManager.swift
Fix #305 
* 「確定」アクションを実行する前に最低一度は`setResult`がなされるべきだが、なされていなかった
* 最適化ロジックを修正し、この問題を解決した
> [Fix] アクション列の最適化のロジックの不具合を修正

- AzooKeyCore/Sources/AzooKeyUtils/AzooKeyKeyboardViewExtension.swift
- AzooKeyCore/Sources/AzooKeyUtils/KeyboardSetting/BoolKeyboardSetting.swift
- AzooKeyCore/Sources/KeyboardViews/ApplicationSpecificKeyboardViewSettingProvider.swift
- AzooKeyCore/Sources/KeyboardViews/VariableStates.swift
- AzooKeyCore/Sources/KeyboardViews/View/KeyboardBar/KeyboardBarView.swift
- AzooKeyCore/Sources/KeyboardViews/View/KeyboardBar/ReflectStyleCursorBar.swift
- AzooKeyCore/Sources/KeyboardViews/View/KeyboardBar/SliderStyleCursorBar.swift
- MainApp/Setting/SettingTab.swift
- Resources/Localizable.xcstrings
* 「新しいカーソルバー」の試験版表記を削除
* ジェスチャを調整し細かい調整をしやすく
* アイコンにスライドを促すアニメーションを追加した
> [Fix] カーソルバーのデザインや挙動を整理

- AzooKeyCore/Sources/KeyboardViews/View/QwertyKeyboard/KeyView/QwertyFunctionalKeyModel.swift
- AzooKeyCore/Sources/KeyboardViews/View/QwertyKeyboard/KeyView/QwertyKeyView.swift
> [Fix] 削除キーを長押ししても削除が発火しない問題を修正

- MainApp/Customize/CustomizeTabView.swift
- MainApp/Setting/SettingTab.swift
> [Refactoring] Use requestReviewAction instead of old impl

- MainApp/Customize/CustomizeTabWalkthrough.swift
> [Fix] broken layout

- AzooKeyCore/Sources/KeyboardViews/View/KeyboardBar/KeyboardBarView.swift
> [Feature] 操作がない場合に自動でカーソルバーを非表示に変更

- AzooKeyCore/Sources/KeyboardViews/View/KeyboardBar/ReflectStyleCursorBar.swift
Reflect styleのカーソルバーに表示される文字が更新されなくなる問題があったので、これを修正した
> [BUG] カーソルバーに表示される文字が更新されなくなる問題を修正

- AzooKeyCore/Sources/KeyboardViews/Design.swift
- AzooKeyCore/Sources/KeyboardViews/View/Components/KeyLabel.swift
- AzooKeyCore/Sources/KeyboardViews/View/CustomKeybaord/CustomKeyboard.swift
- AzooKeyCore/Sources/KeyboardViews/View/FlickKeyboard/FlickKeyboardView.swift
- AzooKeyCore/Sources/KeyboardViews/View/FlickKeyboard/SuggestView/FlickSuggestView.swift
> [Design] キーボードフリック時のSuggestViewを変更

- AzooKeyCore/Sources/KeyboardViews/View/FlickKeyboard/KeyView/FlickKeyView.swift
フリックのサジェストが消えるのを少し遅らせることで、「フリックした感」が高まるようにした
> [Design] add dismiss delay to flick suggests

- MainApp/Theme/ThemeTab.swift
- Resources/Localizable.xcstrings
> [Design] 着せ替えタブのデザインを改善

- AzooKeyCore/Sources/KeyboardViews/VariableStates.swift
原因不明のクラッシュレポートが数件届いており、どうやらTabManagerでBAD_ACCESSが発生していそう。これで治るかは不明だが悪い種類の変更ではないのでやる。
> [Fix] TabManagerへのアクセスでBAD_ACCESSが発生している問題を修正

- AzooKeyCore/Sources/AzooKeyUtils/AzooKeyKeyboardViewExtension.swift
- AzooKeyCore/Sources/AzooKeyUtils/KeyboardSetting/BoolKeyboardSetting.swift
- AzooKeyCore/Sources/KeyboardViews/ApplicationSpecificKeyboardViewSettingProvider.swift
- AzooKeyCore/Sources/KeyboardViews/View/KeyboardBar/KeyboardBarView.swift
- Keyboard/Display/InputManager.swift
- MainApp/Setting/SettingTab.swift
> [Feature] カーソルバーの自動非表示を隠し機能化

- MainApp/Customize/EditingTenkeyCustardView.swift
> [Fix] New design for preview

- AzooKeyCore/Sources/KeyboardViews/View/SpecialTabs/EmojiTab.swift
> [Design] 絵文字タブの戻るボタンを大きくした

- AzooKeyCore/Sources/AzooKeyUtils/AzooKeyKeyboardViewExtension.swift
- AzooKeyCore/Sources/AzooKeyUtils/KeyboardSetting/BoolKeyboardSetting.swift
- AzooKeyCore/Sources/KeyboardViews/ApplicationSpecificKeyboardViewSettingProvider.swift
- AzooKeyCore/Sources/KeyboardViews/View/FlickKeyboard/FlickDataProvider.swift
- AzooKeyCore/Sources/KeyboardViews/View/FlickKeyboard/KeyView/FlickNextCandidateKeyModel.swift
- AzooKeyCore/Sources/KeyboardViews/View/KeyboardBar/ResultBar.swift
- AzooKeyCore/Sources/KeyboardViews/View/QwertyKeyboard/QwertyDataProvider.swift
- MainApp/Setting/SettingTab.swift
- Resources/Localizable.xcstrings
> [Feature] Add 'Next Candidate' option

- AzooKeyCore/Sources/KeyboardViews/View/KeyboardBar/ResultBar.swift
予測変換のアニメーションがやや過剰であると指摘があり、実際その通りだと思うので削減を行う
> [Design] アニメーションを削減

- MainApp/UpdateInformationView.swift
- azooKey.xcodeproj/project.pbxproj
> [Release] Version 2.2.2

- AzooKeyCore/Sources/KeyboardViews/View/KeyboardBar/ResultBar.swift
- Resources/Localizable.xcstrings
> [Feature] 誤変換のレポート操作を分かりやすくした

- AzooKeyCore/Sources/KeyboardViews/View/QwertyKeyboard/KeyView/QwertyLanguageSwitchKeyModel.swift
- AzooKeyCore/Sources/KeyboardViews/View/QwertyKeyboard/QwertyDataProvider.swift
> [Fix] ラベルが消失する不具合を修正

- AzooKeyCore/Sources/KeyboardViews/Tab.swift
- AzooKeyCore/Sources/KeyboardViews/TabManager.swift
- AzooKeyCore/Sources/KeyboardViews/View/CustomKeybaord/CustomKeyboard.swift
- AzooKeyCore/Sources/KeyboardViews/View/KeyboardView.swift
- AzooKeyCore/Sources/KeyboardViews/View/QwertyKeyboard/KeyView/QwertyChangeKeyboardKeyModel.swift
- AzooKeyCore/Sources/KeyboardViews/View/QwertyKeyboard/KeyView/QwertyConditionalKeyModel.swift
- AzooKeyCore/Sources/KeyboardViews/View/QwertyKeyboard/QwertyDataProvider.swift
> [Fix] shiftと地球儀キーの関係を整理

- MainApp/Customize/CodableActionDataEditor.swift
- Resources/Localizable.xcstrings
> [Feature] CustardのActionエディタを完全な実装にする

- MainApp/Customize/CustardInformationView.swift
Fix #156 
* これまではキーボード内部で作成したカスタムタブしか編集できなかった
* #399 のおかげで任意のアクションが編集可能になったため、外部から読み込んだテンキーのカスタムタブデータも編集可能になった
> [Feature] 外部から読み込んだテンキーのカスタムタブデータを編集できるように変更

- MainApp/Info.plist
> [Feature] Add ITSAppUsesNonExemptEncryption=NO

- MainApp/PrivacyInfo.xcprivacy
- azooKey.xcodeproj/project.pbxproj
> [Feature] Privacy Manifestを追加

- azooKey.xcodeproj/project.pbxproj
> [Feature] update version

- MainApp/Info.plist
#448 の追加対応
https://github.com/ensan-hcl/azooKey/actions/runs/8587479098/job/23531177973
> [Fix] アセットのバリデーションエラーを修正

- MainApp/General/SearchQueriedView.swift
- MainApp/Setting/SettingTab.swift
- Resources/Localizable.xcstrings
- azooKey.xcodeproj/project.pbxproj
設定画面で設定項目を検索できるようにした。動いている様子はXにあげた
https://x.com/miwa_ensan/status/1776890398952284341
> [Feature] 設定画面で項目検索ができるようにした

- MainApp/PrivacyInfo.xcprivacy
* ちゃんとキーを指定するように変更
* UserDefaultsを使う理由を変更
> [Fix] Privacy Manifestの対応を修正

- AzooKeyCore/Package.swift
- AzooKeyCore/Sources/AzooKeyUtils/AppVersion.swift
- AzooKeyCore/Sources/AzooKeyUtils/SharedStore.swift
- AzooKeyCore/Sources/KeyboardViews/InternalSettings/EmojiTabExpandModePreference.swift
- AzooKeyCore/Sources/KeyboardViews/InternalSettings/KeyboardInternalSettingManager.swift
- AzooKeyCore/Sources/KeyboardViews/InternalSettings/OneHandedModeSetting.swift
- AzooKeyCore/Sources/KeyboardViews/InternalSettings/TabCharacterPreference.swift
- AzooKeyCore/Sources/KeyboardViews/TabBarData.swift
- AzooKeyCore/Sources/KeyboardViews/VariableStates.swift
- AzooKeyCore/Sources/SwiftUIUtils/UserDefaultsManager.swift
- MainApp/InternalSetting/ContainerInternalSetting.swift
- MainApp/InternalSetting/WalkthroughState.swift
- MainApp/UpdateInformationView.swift
> [Feature] AzooKeyKanaKanjiConverterを0.7系に更新

- AzooKeyCore/Sources/KeyboardViews/View/SpecialTabs/ClipboardHistoryTab.swift
> [Feature] コピー履歴タブに戻るボタンを追加

- Keyboard/Display/KeyboardViewController.swift
> fix: iOS 18以降でレイアウトが崩れる問題を修正

- MainApp/Setting/Template/TemplateEditingView.swift
- MainApp/Setting/Template/TemplateListView.swift
そのほか、monospacedDigitを設定して数字が切り替わる際にガタガタする問題を修正
> fix: テンプレートの編集画面でズレを負に設定しづらくなっていた問題を修正

- AzooKeyCore/Package.swift
- AzooKeyCore/Sources/KeyboardViews/InternalSettings/EmojiTabExpandModePreference.swift
- AzooKeyCore/Sources/KeyboardViews/InternalSettings/OneHandedModeSetting.swift
- AzooKeyCore/Sources/KeyboardViews/InternalSettings/TabCharacterPreference.swift
- MainApp/UpdateInformationView.swift
* 変換モジュールをロールバック（若干重くなったが、これを直すのはスケジュール的に困難であるため）
* 更新情報を追加
> feat: version 2.3のリリース準備

- MainApp/Customize/CustardInterfaceKeyEditor.swift
- MainApp/Customize/EditingScrollCustardView.swift
- MainApp/Customize/EditingTenkeyCustardView.swift
- MainApp/General/IconNavigationLink.swift
この問題を踏んだ
https://developer.apple.com/forums/thread/720096
> fix: NavigationLinkを押すとfreezeする問題に対処

- AzooKeyCore/Sources/AzooKeyUtils/Custard/CustardManager.swift
- AzooKeyCore/Sources/AzooKeyUtils/KeyboardSetting/BoolKeyboardSetting.swift
- AzooKeyCore/Sources/KeyboardViews/TabBarData.swift
- AzooKeyCore/Sources/KeyboardViews/View/KeyboardBar/TabBar.swift
- MainApp/ContentView.swift
- MainApp/Customize/CustardInformationView.swift
- MainApp/Customize/EditingTabBarView.swift
- MainApp/General/Pickers/SystemIconPicker.swift
- Resources/Localizable.xcstrings
> feat: tabbarの機能改善

- Keyboard/Display/KeyboardViewController.swift
Fix #504 
This pull request refactors the `openURL` functionality in the `KeyboardViewController` class to improve compatibility with iOS 18 and streamline the method's behavior. The changes include replacing the old `openUrl` method with an updated implementation of `openURL` that handles both modern and legacy iOS versions.
* **Updated `openURL` method**:
- Refactored the `openURL` method to support iOS 18's `UIApplication.open` API while maintaining backward compatibility for earlier iOS versions. The method now returns a `Bool` to indicate success and uses `@discardableResult` to allow ignoring the return value.
* **Replaced `openUrl` calls**:
- Replaced calls to the deprecated `openUrl` method with the new `openURL` method to ensure consistent behavior across the codebase.
> fix: open urlが動作していない問題を修正

- AzooKeyCore/Sources/KeyboardViews/TabBarData.swift
- MainApp/Customize/CustomizeTabView.swift
- MainApp/Customize/EditingTenkeyCustardView.swift
> feat: 「拡張」タブを見直し

- AzooKeyCore/Sources/SwiftUIUtils/HelpAlertButton.swift
- MainApp/Customize/CustardInterfaceKeyEditor.swift
> feat: リリース前の微調整

- MainApp/UpdateInformationView.swift
- azooKey.xcodeproj/project.pbxproj
βテストの実施などのためプロジェクト設定を変更し、バージョンを修正
> feat: v2.4.1のための変更

- AzooKeyCore/Sources/KeyboardViews/View/QwertyKeyboard/SuggestView/QwertySuggestView.swift
> fix: 着せ替えの色を修正し、サジェストの描画をわずかに改善

- AzooKeyCore/Sources/AzooKeyUtils/SharedStore.swift
- MainApp/General/BottomSheetView.swift
- MainApp/General/LargeButtonStyle.swift
- MainApp/General/OnEnterBackground.swift
- MainApp/Setting/AdditionalDict/AzooKeyUserDictionary.swift
- MainApp/Setting/SettingTab.swift
- MainApp/Setting/ShareWordView.swift
- Resources/Localizable.xcstrings
* 「この単語をシェア」の機能を明確化した
* 単語が不特定多数のユーザに共有される旨を説明し、送信の前に警告を表示する
* 個人情報を含んではいけない旨を強く示した
* 保存フォームの向き先を変更した
* 備考の入力をサポートした
> feat: 「この単語をシェア」の機能を明確化し、フォームの向き先を変更

- AzooKeyCore/Sources/KeyboardViews/Action.swift
- AzooKeyCore/Sources/KeyboardViews/View/CustomKeyboard/CustomKeyboard.swift
- AzooKeyCore/Sources/KeyboardViews/View/FlickKeyboard/FlickKeyView.swift
see: https://discord.com/channels/1166734354492440638/1166734421609697342/1373946701378883687
> fix: longpress actionがemptyであるかの確認が誤っていたので修正

- MainApp/Customize/CustardInformationView.swift
- MainApp/Customize/EditingTenkeyCustardView.swift
- Resources/Localizable.xcstrings
* fix: ベース英語タブの設定の問題を修正
* feat: カスタムタブ情報の画面からデフォルトを変更できるように改善
> feat: カスタムタブの編集を更新

- azooKey.xcodeproj/project.pbxproj
* バージョン設定をv2.5に変更
* ミニマムのOSバージョンをiOS 17.6に引き上げ
> feat: update to v2.5 for testing

- MainApp/Utils/UserDictionaryUpdater.swift
「今日→2025年09月03日」のような変換候補を登録していると「きょうは」のようなケースにまで「2025年09月03日は」が現れる問題があった。これは有用なケースもあるが、ないほうが多くの場合によい。そこでテンプレート由来の候補はショートカットとして扱うことによってこの問題を修正した。
> feat: テンプレート由来の候補をショートカット扱いするよう変更

- AzooKeyCore/Sources/AzooKeyUtils/SharedStore.swift
- AzooKeyCore/Sources/KeyboardViews/States/ReportSuggestion.swift
- AzooKeyCore/Sources/KeyboardViews/States/ReportSuggestionState.swift
- AzooKeyCore/Sources/KeyboardViews/VariableStates.swift
- Keyboard/Display/KeyboardActionManager+Reporting.swift
- Keyboard/Display/KeyboardActionManager.swift
- Keyboard/Display/KeyboardViewController.swift
- MainApp/Setting/Contribution/ContributionSettingView.swift
* 記号変換などで表示されないように変更
* 一度報告したものはしばらく出さないように変更
* prefix一致の場合は出さないように変更
> feat: 誤変換レポート提案のケースを限定
