Keyboard/Converter/DicdataStore/DicdataStore.swift
Keyboard/Converter/DicdataStore/LearningMemory.swift
Keyboard/Converter/Kana2Kanji/getPrediction.swift

#4 の一環で、CharIDへの変換を削減した。結果として5%程度の高速化が達成できた。
`testFullConversion`のベンチマークとしては
* before
* `getLOUDSDataInRange`が全体の92%
* after
* `getLOUDSDataInRange`が全体の86.5%
という感じ。
特に、keyToCharsの呼び出しはほぼゼロまで抑えられるようになった。

[Performance Tuning] CharIDへの変換を削減し、5%程度の高速化を達成

---

MainApp/Customize/CustardInterfaceKeyEditor.swift
Shared/KeyboardView/View/CustomKeybaord/CustomKeyboard.swift
Shared/en.lproj/Localizable.strings

[Feature] add symbol key like custom key

---

Keyboard/Display/DisplayedTextManager.swift
Keyboard/Display/KeyboardViewController.swift
MainApp/Customize/EditingTenkeyCustardView.swift
MainApp/Setting/CustomKeys/QwertyCustomKeys/QwertyCustomKeysItemView.swift
Shared/Converter/TemplateData.swift
Shared/KeyboardView/View/Components/InKeyboardTextInput/InKeyboardSearchBar.swift
Shared/KeyboardView/View/Components/InKeyboardTextInput/InKeyboardTextEditor.swift
Shared/KeyboardView/View/CustomKeybaord/CustomKeyboard.swift
Shared/KeyboardView/View/FlickKeyboard/FlickDataProvider.swift
Shared/KeyboardView/View/FlickKeyboard/KeyView/FlickKeyView.swift
Shared/KeyboardView/View/QwertyKeyboard/KeyView/QwertyKeyView.swift
Shared/KeyboardView/View/QwertyKeyboard/QwertyDataProvider.swift
azooKey.xcodeproj/project.pbxproj

Swift5.8の`-enable-upcoming-feature ExistentialAny`を適用し、コンパイラがエラーを出すように変更した。
Fix #108

[Refactoring] bare `P` -> `any P`の適用

---

MainApp/ContentView.swift
MainApp/Customize/CustardInformationView.swift
MainApp/General/Pickers/FontPicker.swift
MainApp/Theme/ThemeEditView.swift
MainApp/Theme/ThemeShareView.swift
azooKey.xcodeproj/project.pbxproj

Swift 5.8の`-enable-upcoming-feature ForwardTrailingClosures`を適用した。
* trailing closureであり、デフォルト引数があるために省略されていたクロージャがあるようなケースで、明示的なラベルが必要になった。

[Refactoring] Apply `-enable-upcoming-feature ForwardTrailingClosures`

---

Keyboard/Converter/Converter/Converter.swift
Keyboard/Display/InputManager.swift

UITextCheckerが初回起動時にリソースを読み込む都合で処理に時間がかかるので、タブを開いた時点で前もってリソースを読み込ませることで対応した。
Fix #138

[Bug] 初回の英語タブの利用時に読み込みが遅い問題を修正

---

Shared/KeyboardView/VariableStates.swift

「取り消し」ボタンがキーボードを閉じた後も表示されることがある不具合を修正。

[Fix] increment text changed count when closeKeyboard()

---

Keyboard/Display/DisplayedTextManager.swift

`viewWillDisappear`の実行タイミングは、必ずしもその後の`viewWillAppear`より前とは限らない。

[Bug] キーボードを閉じてすぐに開くとmain proxyが消えてしまう問題を修正

---

MainApp/Setting/AdditionalDict/AzooKeyUserDictionary.swift
MainApp/Setting/AdditionalDict/AzooKeyUserDictionaryData.swift
MainApp/Setting/ContactView.swift
MainApp/Setting/ShareWordView.swift
Shared/SharedStore.swift
Shared/en.lproj/Localizable.strings
azooKey.xcodeproj/project.pbxproj

ユーザ辞書の追加時に「この単語をシェアする」トグルをオンにすることでazooKeyに変換候補の追加を申請できるようにした。「誤変換を報告」と合わせ、ユーザのフィードバックでアプリを改善したい。
Resolved #151

[Feature] 「この単語をシェアする」機能

---

Keyboard/Converter/DicdataStore/DicdataStore.swift

`getLOUDSInRange`の内部実装の不要な計算を除去し、`testFullConversion`において約22%の高速化に成功した。
詳細は[#4](https://github.com/ensan-hcl/azooKey/issues/4#issuecomment-1510381808)を参照

[Performance] testFullConversionを22%(160ms)高速化

---

Keyboard/Converter/DicdataStore/JapaneseNumber.swift
azooKey.xcodeproj/project.pbxproj
azooKeyTests/KeyboardTests/DicdataStoreTests/JapaneseNumberConversionTests.swift

Fix #167 
Japanese Number Conversionの実装で考慮漏れがあり、そこから不具合が起きていた。

[Fix] 「マルマン」「マルセン」と入力した際にキーボードがクラッシュする不具合を修正

---

MainApp/Tips/Articles/iOS14TerminationNews.swift

* ReleaseビルドはViolationをエラーにするが、これが通らなかったので修正

[Fix] Suppress Type Name Violation in SwiftLint

---

MainApp/EnableAzooKeyView/EnableAzooKeyView.swift
MainApp/MainApp.swift
MainApp/Utils/checkKeyboardActivation.swift

Resolve #237 
* "AppleKeyboards"よりも`UITextInputMode.activeInputModes`の方が更新タイミングが遅い（`onEnterForeground`のタイミングでは更新されていない）ので、taskとして定期実行して動作を再現した。
* 合わせて、UITextInputMode.InputModeDidChangeNotificationによる有効化状態のチェックを追加した

[Refactoring] UserDefaultsの"AppleKeyboards"は今後使えなくなるので、UITextInputModeで代替した

---

azooKey.xcodeproj/project.pbxproj

developブランチのアプリ内のバージョンは変更になるが、正式リリースとしてはAppStoreに出したものを2.2とする。

[Version] Update Version for TestFlight

---

AzooKeyCore/Sources/AzooKeyUtils/AzooKeyKeyboardViewExtension.swift
AzooKeyCore/Sources/KeyboardViews/ApplicationSpecificKeyboardViewSettingProvider.swift
AzooKeyCore/Sources/KeyboardViews/VariableStates.swift
AzooKeyCore/Sources/KeyboardViews/View/QwertyKeyboard/KeyView/QwertyKeyModel.swift
AzooKeyCore/Sources/KeyboardViews/View/QwertyKeyboard/KeyView/QwertyShiftKeyModel.swift
AzooKeyCore/Sources/KeyboardViews/View/QwertyKeyboard/QwertyDataProvider.swift
Keyboard/Display/KeyboardActionManager.swift

* #252 に基づいてシフトキーの実装を追加した（Resolve #251 ）
* #251 ではone-offのステートを追加することを検討したが、一旦は愚直な実装でもそこまで悪くないと判断した
* 現在は`ApplicationSpecificKeyboardViewSettingProvider`の中で`useShiftKey`というパラメータを追加して制御している。一旦常に`false`にした。
* azooKey本体のユーザ設定として露出させるかは別途判断する。

[Feature] シフトキーの実装を追加

---

AzooKeyCore/Sources/AzooKeyUtils/AzooKeyTheme/AzooKeySpecificTheme.swift
AzooKeyCore/Sources/KeyboardThemes/ThemeData.swift
AzooKeyCore/Sources/KeyboardViews/View/FlickKeyboard/KeyView/FlickKeyView.swift
AzooKeyCore/Sources/KeyboardViews/View/QwertyKeyboard/KeyView/QwertyKeyView.swift

* #194 の処理
* azooKeyの着せ替えエディタに露出させるかは別途検討する

[Feature] `ThemeData`にShadowの設定を追加し、標準キーボード風の影を追加できるようにした

---

MainApp/LOUDSLogic/LOUDSBuilder.swift
azooKeyTests/KeyboardTests/DicdataStoreTests/DicdataStoreTests.swift

Fix #261 
こちらのPRと合わせて修正。
https://github.com/ensan-hcl/AzooKeyKanaKanjiConverter/pull/13

[Fix] \nが変換に現れる問題を修正

---

azooKey.xcodeproj/project.pbxproj

AzooKeyKanaKanjiConverterを二重管理していたので、片方に寄せた。

[Refactoring] Simplify dependency structure

---

AzooKeyCore/Sources/KeyboardViews/Action.swift
AzooKeyCore/Sources/KeyboardViews/ActionUtils.swift
AzooKeyCore/Sources/KeyboardViews/Design.swift
AzooKeyCore/Sources/KeyboardViews/States.swift
AzooKeyCore/Sources/KeyboardViews/VariableStates.swift
AzooKeyCore/Sources/KeyboardViews/View/CustomKeybaord/SimpleKeyView/SimpleKeyModel.swift
AzooKeyCore/Sources/KeyboardViews/View/FlickKeyboard/KeyView/FlickEnterKeyModel.swift
AzooKeyCore/Sources/KeyboardViews/View/QwertyKeyboard/KeyView/QwertyEnterKeyModel.swift
AzooKeyCore/Sources/KeyboardViews/View/QwertyKeyboard/KeyView/QwertyKeyModelProtocol.swift
Keyboard/Display/InputManager.swift
Keyboard/Display/KeyboardActionManager.swift

#272 を考えていたが、「edit」ボタンは大して便利ではない割にメンテナンスコストがそこそこかかっている。このため、editボタンは廃止する。

[Feature] Remove 'edit'

---

AzooKeyCore/Sources/KeyboardViews/View/CustomKeybaord/SimpleKeyView/SimpleKeyModel.swift
AzooKeyCore/Sources/KeyboardViews/View/FlickKeyboard/KeyView/FlickAaKeyModel.swift
AzooKeyCore/Sources/KeyboardViews/View/FlickKeyboard/KeyView/FlickChangeKeyboardKeyModel.swift
AzooKeyCore/Sources/KeyboardViews/View/FlickKeyboard/KeyView/FlickEnterKeyModel.swift
AzooKeyCore/Sources/KeyboardViews/View/FlickKeyboard/KeyView/FlickKanaSymbolsKeyModel.swift
AzooKeyCore/Sources/KeyboardViews/View/FlickKeyboard/KeyView/FlickKeyModel.swift
AzooKeyCore/Sources/KeyboardViews/View/FlickKeyboard/KeyView/FlickKogakiKeyModel.swift
AzooKeyCore/Sources/KeyboardViews/View/FlickKeyboard/KeyView/FlickSpaceKeyModel.swift
AzooKeyCore/Sources/KeyboardViews/View/FlickKeyboard/KeyView/FlickTabKeyModel.swift
AzooKeyCore/Sources/KeyboardViews/View/QwertyKeyboard/KeyView/QwertyAaKeyModel.swift
AzooKeyCore/Sources/KeyboardViews/View/QwertyKeyboard/KeyView/QwertyChangeKeyboardKeyModel.swift
AzooKeyCore/Sources/KeyboardViews/View/QwertyKeyboard/KeyView/QwertyEnterKeyModel.swift
AzooKeyCore/Sources/KeyboardViews/View/QwertyKeyboard/KeyView/QwertyFunctionalKeyModel.swift
AzooKeyCore/Sources/KeyboardViews/View/QwertyKeyboard/KeyView/QwertyKeyModel.swift
AzooKeyCore/Sources/KeyboardViews/View/QwertyKeyboard/KeyView/QwertyLanguageSwitchKeyModel.swift
AzooKeyCore/Sources/KeyboardViews/View/QwertyKeyboard/KeyView/QwertyShiftKeyModel.swift
AzooKeyCore/Sources/KeyboardViews/View/QwertyKeyboard/KeyView/QwertySpaceKeyModel.swift
AzooKeyCore/Sources/KeyboardViews/View/QwertyKeyboard/KeyView/QwertyTabKeyModel.swift
AzooKeyCore/Sources/KeyboardViews/View/SpecialTabs/EmojiTab.swift

#281 の一環。型パラメータのoverideはSwift5.9以降でwarningが出るので修正。

[Refactoring] 型パラメータのoverrideを避ける

---

MainApp/EnableAzooKeyView/EnableAzooKeyView.swift
MainApp/Utils/checkKeyboardActivation.swift

下記の事情で今後デバッグ用にBundleNameを変更することが増えそうなので、チェックを緩和しておく。
https://x.com/miwa_ensan/status/1705839363391930736?s=20

[Chore] relax bundle name check condition

---

AzooKeyCore/Sources/KeyboardViews/View/KeyboardBar/ResultBar.swift

* アニメーションでタブバーボタンが候補の後ろを通っていて気持ち悪かったので、zIndexでフロントにした

[Fix] apply zIndex to make tab bar button front

---

AzooKeyCore/Package.swift
azooKey.xcodeproj/project.pbxproj

Fix #309 
`develop`ブランチではcommit id直接指定を許可し、`main`では`upToMinor`の利用のみとする。

[Fix] 依存パッケージのバージョンを固定し、決め方について追記

---

AzooKeyCore/Sources/KeyboardViews/View/QwertyKeyboard/KeyView/QwertyKeyView.swift
AzooKeyCore/Sources/KeyboardViews/View/QwertyKeyboard/KeyView/QwertyVariationsView.swift

[Feature] QwertyKeyViewのサジェストに薄いシャドウを追加

---

AzooKeyCore/Sources/KeyboardViews/AzooKeyIcon.swift
MainApp/Customize/CustomizeTabWalkthrough.swift
MainApp/Customize/EditingTabBarView.swift
MainApp/EnableAzooKeyView/EnableAzooKeyView.swift
MainApp/EnableAzooKeyView/EnableAzooKeyViewComponent.swift
MainApp/General/Focus.swift
MainApp/General/HeaderLogoView.swift
MainApp/General/LargeButtonStyle.swift
MainApp/Setting/CustomKeys/FlickCustomKeys/CustomKeySettingFlickKeyView.swift
MainApp/Setting/CustomKeys/QwertyCustomKeys/QwertyCustomKeysItemView.swift
MainApp/Setting/OpenSourceSoftwaresLicenseView.swift
MainApp/Tips/TipsView.swift
Resources/Localizable.xcstrings

* AckのViewでazooKeyのアイコンが動くようにした(iOS 17+)
* focusの実装を調整し、より美しいshadowが付くようにした
* tab barの編集中にアイテムを追加した際、画面が下にスクロールするようにした
* tips viewのヘッダーにlogoを表示する方法をよりSwiftUI-nativeにした

[Feature] デザインを改善

---

AzooKeyCore/Sources/KeyboardViews/TemporalMessage.swift
AzooKeyCore/Sources/KeyboardViews/View/Components/TemporalMessageView.swift
AzooKeyCore/Sources/KeyboardViews/View/KeyboardView.swift

誤変換の報告や学習のリセット後にTemporalMessageViewが非表示にならない問題があったため、これに対処した。

[Bug] TemporalMessageViewが消えないことがある問題に対処

---

AzooKeyCore/Sources/KeyboardViews/VariableStates.swift
AzooKeyCore/Sources/KeyboardViews/View/KeyboardBar/ReflectStyleCursorBar.swift
Keyboard/Display/InputManager.swift
Keyboard/Display/KeyboardActionManager.swift

コミットがごちゃごちゃになってしまった。
* Fix #334 （原因はdrawingGroup()だった）
* Reflect StyleのCursor Bar StateをVariableStatesに持たせていたのをやめた
* 行を跨ぐケースで #277 が動作しない問題を修正
* Reflect Styleのカーソルバーで文字がガチャガチャと移動する問題を緩和した

[Fix] CursorBar周りを整えた

---

AzooKeyCore/Sources/KeyboardViews/KeyboardFeedback.swift

KeyboardFeedbackの実装の中で`AudioServicesPlaySystemSound`を呼んでいる部分が怪しいのではないかと考え、これを`MainActor`以外でも実行できるように変更した。
#336 を解決することを期待しているが、様子見。悪くはならないはず。

[Fix] KeyboardFeedbackの実装のうち、MainActorで実行する処理とそうでない処理を分別した

---

AzooKeyCore/Sources/KeyboardViews/Design.swift
AzooKeyCore/Sources/KeyboardViews/View/CustomKeybaord/CustomKeyboard.swift
AzooKeyCore/Sources/KeyboardViews/View/FlickKeyboard/FlickKeyboardView.swift
AzooKeyCore/Sources/KeyboardViews/View/QwertyKeyboard/QwertyKeyboardView.swift
AzooKeyCore/Sources/KeyboardViews/View/SpecialTabs/ClipboardHistoryTab.swift
AzooKeyCore/Sources/KeyboardViews/View/SpecialTabs/EmojiTab.swift
MainApp/Customize/EditingTenkeyCustardView.swift

レイアウトの計算からKeyboardLayoutへの依存性を抜いた。これによって端末によって微妙にキーサイズやスペーシングが変わるが、多くの場合は気づかないと思う。

[Design] 余白をKeyboardLayout非依存にした

---

MainApp/Customize/EditingScrollCustardView.swift
MainApp/Customize/EditingTenkeyCustardView.swift

* リファクタリング
* `GeometryReader`を除去
* deprecatedなAPIを排除
* スクロール式カスタムタブのプレビューをフリック式と同様に変更

[Refactoring & Design] スクロール式カスタムタブのプレビューをすり合わせ

---

README.md

* Discordチャンネルへのリンクを表示
* AzooKeyKanaKanjiConverterへのリンクを表示

[Meta] Update README.md

---

AzooKeyCore/Sources/AzooKeyUtils/AzooKeyKeyboardViewExtension.swift
AzooKeyCore/Sources/AzooKeyUtils/KeyboardSetting/BoolKeyboardSetting.swift
AzooKeyCore/Sources/AzooKeyUtils/SharedStore.swift
AzooKeyCore/Sources/KeyboardViews/ApplicationSpecificKeyboardViewSettingProvider.swift
AzooKeyCore/Sources/KeyboardViews/View/QwertyKeyboard/KeyView/QwertyShiftKeyModel.swift
AzooKeyCore/Sources/KeyboardViews/View/QwertyKeyboard/QwertyDataProvider.swift
MainApp/MainApp.swift
MainApp/Setting/SettingTab.swift

Resolve #379 
* シフトキーをVersion 2.2で導入したが、位置がイマイチでキーがガタガタ動いていた
* そこでVersion 2.2.3以降はデフォルトでシフトキーの位置を左下にすることで、この問題を解決した（leftbottom）
* 既存のシフトキーのユーザは設定アプリで「シフトキーの古い挙動を使う」をオフにすることで、新しいバージョンのシフトキーを利用できる
* iOS 18以降はこの挙動を完全に廃止する
* 新規のユーザ（Version 2.2.3以降にダウンロードした人）は「シフトキーの古い挙動を使う」オプションは存在せず、初めからleftbottomで表示する
leftbottomの場合にピリオドキーを配置したのに合わせて、日本語キーの「ー」の長押しに句読点などを配置した

[Feature] シフトキーの配置を改善

---

AzooKeyCore/Package.swift
Keyboard/Display/InputManager.swift

fix #410 
* AZKKCのバージョンを上げた
* TextReplacerをこちらから渡すことで、絵文字のゼロクエリ予測変換をサポートした

[Feature] Update AZKKC version and support new text replacer API

---

.github/workflows/build.yml

This pull request adds a build workflow for the iOS app. The workflow includes steps to build, archive, export, and upload the app to App Store Connect.
It's also important to note that the required Swift tools version 5.9.0 requires the use of macos-14 instead of macos-latest to ensure compatibility and successful builds.

[Feature] Add build workflow for iOS app

---

.github/workflows/swift.yml

This pull request adds a cache action to the GitHub workflow in order to cache the Swift build artifacts. This will improve the build time and reduce the need for rebuilding the dependencies.

Add cache action for Swift build artifacts

---

AzooKeyCore/Sources/AzooKeyUtils/Custard/UserMadeCustard.swift
AzooKeyCore/Sources/KeyboardViews/View/CustomKeybaord/CustomKeyboard.swift
AzooKeyCore/Sources/KeyboardViews/View/CustomKeybaord/SimpleKeyView/SimpleKeyView.swift
MainApp/Customize/CustardInformationView.swift
MainApp/Customize/CustardInterfaceKeyEditor.swift
MainApp/Customize/EditingScrollCustardView.swift
MainApp/Customize/EditingTenkeyCustardView.swift
Resources/Localizable.xcstrings

Resolve #428 
* スクロール式カスタムタブの編集UIを多機能化
* Drag&Dropによる並び替えをサポート
* Context Menu経由の削除をサポート
* キーの詳細な編集をサポート
* UserMadeScrollCustardのCodableを修正
* 中身のwordsをkeysに置き換えた
* UserMadeKeyDataにidを追加

[Feature] 改善されたスクロール式カスタムタブの編集UIを実装

---

Gen/scripts/emoji.py

[Fix] 握手絵文字のバリエーションが誤って右パンチ絵文字のバリエーションとして扱われていた問題を修正

---

AzooKeyCore/Sources/KeyboardViews/View/KeyboardView.swift

Discordでの議論とGoogle Form経由の要望に基づいてキーボードバーの挙動を調整してみた
（Discordのリンクを閲覧するには[https://discord.gg/dY9gHuyZN5](https://discord.gg/dY9gHuyZN5)からazooKeyのDiscordに参加してください
* https://discord.com/channels/1166734354492440638/1166734421609697342/1226359615705452594
* https://discord.com/channels/1166734354492440638/1205918378355851296/1229354165344669756
* https://discord.com/channels/1166734354492440638/1166734421609697342/1229394785094340609

[fix] キーボードバーの判定が広すぎる問題を修正

---

.github/workflows/upload-build.yml

This pull request removes the unnecessary build step from the project's workflow. The build step was previously included in the workflow but is no longer needed. This change simplifies the workflow and improves efficiency.

Remove unnecessary build step

---

.github/workflows/build-on-push.yml
.github/workflows/upload-build.yml

This pull request adds a cache for the DerivedData folder in the GitHub Actions workflow. This will improve build times by reusing previously built artifacts.

Add cache for DerivedData in GitHub Actions workflow

---

.github/workflows/codeql.yml

This pull request adds a CodeQL workflow for automated code scanning. The workflow file is included in the `.github/workflows` directory and is named `codeql.yml`. The workflow is triggered on push and pull request events on the `develop` branch, as well as on a weekly schedule. The workflow runs CodeQL analysis on the repository's codebase using the supported languages specified in the matrix. The analysis is performed on either `ubuntu-latest` or `macos-latest` runners, depending on the language. The workflow also sets the necessary permissions for the analysis, including read access to security events, packages, actions, and contents.

Add CodeQL workflow for automated code scanning

---

AzooKeyCore/Sources/KeyboardViews/KeyboardTab.swift
AzooKeyCore/Sources/KeyboardViews/TabManager.swift
AzooKeyCore/Sources/KeyboardViews/VariableStates.swift
AzooKeyCore/Sources/KeyboardViews/View/FlickKeyboard/KeyView/FlickTabKeyModel.swift
AzooKeyCore/Sources/KeyboardViews/View/KeyboardView.swift
MainApp/General/KeyboardPreview.swift
MainApp/Setting/KeyboardLayout/KeyboardLayoutSettingItemView.swift
MainApp/Theme/ThemeEditView.swift
MainApp/Theme/ThemeTab.swift

Xcode16 betaを試していたところ、SwiftUIに新規に追加された`Tab`のせいで既存の`Tab`との衝突が発見することに気付いた。この問題の修正のため、既存の`Tab`を`KeyboardTab`にリネームした。

[Chore] Tab -> KeyboardTab (because of SwiftUI.Tab)

---

AzooKeyCore/Sources/KeyboardViews/UserActionManager.swift
AzooKeyCore/Sources/KeyboardViews/View/CustomKeybaord/SimpleKeyView/SimpleKeyView.swift
AzooKeyCore/Sources/KeyboardViews/View/FlickKeyboard/KeyView/FlickKeyView.swift
AzooKeyCore/Sources/KeyboardViews/View/QwertyKeyboard/KeyView/QwertyKeyView.swift
Keyboard/Display/KeyboardActionManager.swift

Related to #500, but not resolve
長押し判定の時間は0.4秒を前提にコードを作っていたが、これに関連する変数を整理し（原理的には）切り替えられるようにした。

refactor: 長押し時間のハードコードを止め、変数を切り替えるだけで容易に設定できるように変更

---

AzooKeyCore/Sources/KeyboardViews/View/Components/ResizingRect.swift
AzooKeyCore/Sources/KeyboardViews/View/CustomKeybaord/SimpleKeyView/SimpleKeyView.swift
AzooKeyCore/Sources/KeyboardViews/View/FlickKeyboard/KeyView/FlickKeyView.swift
AzooKeyCore/Sources/KeyboardViews/View/KeyboardBar/ReflectStyleCursorBar.swift
AzooKeyCore/Sources/KeyboardViews/View/KeyboardBar/SliderStyleCursorBar.swift
AzooKeyCore/Sources/KeyboardViews/View/KeyboardView.swift
AzooKeyCore/Sources/KeyboardViews/View/QwertyKeyboard/KeyView/QwertyKeyView.swift
MainApp/Customize/CustomizeTabWalkthrough.swift
MainApp/Customize/EditingTenkeyCustardView.swift
MainApp/General/LargeButtonStyle.swift
MainApp/Setting/CustomKeys/FlickCustomKeys/CustomKeySettingFlickKeyView.swift
MainApp/Setting/CustomKeys/QwertyCustomKeys/QwertyCustomKeysItemView.swift
MainApp/Setting/FontSizeSetting/FontSizeSettingItemView.swift
MainApp/Theme/ThemeShareView.swift
MainApp/Theme/ThemeTab.swift

refactor: `overlay`と`background`でdeprecated APIを使っている部分を修正

---

AzooKeyCore/Sources/KeyboardThemes/ThemeColor.swift

This pull request modifies the `ThemeColor` enum in `ThemeColor.swift` to improve how colors are handled, particularly addressing an issue with the `.clear` color. The most important change ensures that `.clear` now uses a nearly transparent color to maintain interaction hit testing.
* [`ThemeColor.swift`](diffhunk://#diff-ceee9c3a55ce35622be38069a2eb1a04dae16cebf0fed3ae7b3377946a5ece4cL53-R67): Updated the `.clear` case to use `Color(white: 0, opacity: 0.001)` instead of the default `.clear`, preventing loss of touch interaction while maintaining near-transparency. This change ensures better user experience when `.clear` is used in interactive views.

feat: 当たり判定が壊れていた問題を修正

---

AzooKeyCore/Sources/KeyboardViews/View/QwertyKeyboard/KeyView/QwertyAaKeyModel.swift

This pull request includes a small but significant change to the `QwertyAaKeyModel` in the `QwertyKeyboard` implementation. The change updates the appearance of the key when it is not in a caps-locked state.
* [`AzooKeyCore/Sources/KeyboardViews/View/QwertyKeyboard/KeyView/QwertyAaKeyModel.swift`](diffhunk://#diff-2898af63e4a2c39d06650571468795631551e9d3872246f2cf8ed8a48caef704L36-R36): Replaced the key label from an image (`textformat.alt`) to a text label (`Aa`) when the caps lock is not active. This likely improves clarity for users.

fix: textformat.altはロケール依存で期待した動作をしていないので、テキストに置き換え

---

MainApp/Customize/EditingTabBarView.swift

fix #509 
This pull request introduces several updates to the `EditingTabBarView.swift` file, focusing on improving the user interface and behavior of the tab bar editing experience. The most important changes include updating button icons, refining label type switching logic, enhancing picker styles, and dynamically updating text labels.
* Updated the icon for the "azooKeyを開く" button from `gear` to `gearshape` to align with system consistency.
* Added the `.labelStyle(.titleOnly)` modifier to the picker to improve its visual appearance by displaying only the title.
* Refined the logic for switching label types in `TabNavigationViewItemLabelTypePicker` to handle transitions between `.text` and `.image` more robustly, avoiding unnecessary resets when the type remains the same.
* Added an …

fix: タブバー編集画面の問題を修正

---

.github/ISSUE_TEMPLATE/bug-report--不具合の報告-.md
.github/ISSUE_TEMPLATE/feature-request--機能の提案-.md
.github/ISSUE_TEMPLATE/question--質問-.md

This pull request updates the issue templates to improve clarity and consistency in titles and user responses. The changes include standardizing the title format across templates and adding prompts to encourage user engagement.
* [`.github/ISSUE_TEMPLATE/bug-report--不具合の報告-.md`](diffhunk://#diff-5cf4ec225d3a5faa5ac350c09efb0ee7cec7e589709a5e9c8df723584b320fdcL4-R4): Updated the title format to "bug: <Description of bug>" for consistency and added a "Yes/No" prompt to indicate if the user can assist with ongoing communication to fix the bug. [[1]](diffhunk://#diff-5cf4ec225d3a5faa5ac350c09efb0ee7cec7e589709a5e9c8df723584b320fdcL4-R4) [[2]](diffhunk://#diff-5cf4ec225d3a5faa5ac350c09efb0ee7cec7e589709a5e9c8df723584b320fdcR33)
* [`.github/ISSUE_TEMPLATE/feature-request--機能の提案-.md`](diffhunk:// …

repo: issueテンプレートのフォーマットを変更

---

AzooKeyCore/Sources/AzooKeyUtils/KeyboardSetting/FlickCustomKeyKeyboardSetting.swift
AzooKeyCore/Sources/KeyboardViews/ExternalSetting/FlickCustomKeySetting.swift
AzooKeyCore/Sources/KeyboardViews/States.swift
AzooKeyCore/Sources/KeyboardViews/TabBarData.swift
AzooKeyCore/Sources/KeyboardViews/View/CustomKeybaord/CustomKeyboard.swift
AzooKeyCore/Sources/KeyboardViews/View/QwertyKeyboard/KeyView/QwertyLanguageSwitchKeyModel.swift
AzooKeyCore/Sources/KeyboardViews/View/QwertyKeyboard/KeyView/QwertyTabKeyModel.swift
MainApp/Setting/CustomKeys/FlickCustomKeys/FlickCustomKeySettingView.swift

* 「abc」キーのラベルをOS標準と揃えて「ABC」に変更
* Qwertyで切替キーがある場合、「A」を「ABC」に、「あ」を「あいう」キーに変更
* 位置周りは変更無し

feat: use consistent label for both flick/qwerty by default

---

AzooKeyCore/Sources/KeyboardViews/VariableStates.swift
AzooKeyCore/Sources/KeyboardViews/View/SpecialTabs/EmojiTab.swift
Keyboard/Display/KeyboardActionManager.swift

これまでRecent Emojiは即時更新だったため、Recent Emoji内で絵文字を連打すると勝手に順序が入れ替わり、異なる絵文字が入力されてしまう問題があった。この問題は特に同じ絵文字を連打する際に深刻だった。
そこで、表示が更新されるタイミングをジャンルの切替時に絞り、Recent Emojiが表示されている間は更新が生じないようにした。

fix: recent emojiが頻繁に更新され過ぎる問題を修正

---

AzooKeyCore/Sources/KeyboardViews/View/Components/KeyBackground.swift
AzooKeyCore/Sources/KeyboardViews/View/CustomKeybaord/CustomKeyboard.swift
AzooKeyCore/Sources/KeyboardViews/View/CustomKeybaord/SimpleKeyView/SimpleKeyView.swift
AzooKeyCore/Sources/KeyboardViews/View/FlickKeyboard/KeyView/FlickKeyView.swift
AzooKeyCore/Sources/KeyboardViews/View/QwertyKeyboard/KeyView/QwertyKeyView.swift

厳密には原因不明だが、新テーマにおいてshadowが時おり表示されないことがあったので、実装を書き換えたところ良くなった。また、キーボードごとの表示の一貫性のため、`KeyBackground`の`View`を別途導入し、すべての環境でこれをベースとして使うようにした。

fix: 時おりshadowが表示されなくなっていた問題を修正

---

AzooKeyCore/Sources/KeyboardViews/View/KeyboardBar/ResultBar.swift

これまでタブバーボタンの位置には3箇所あり
1. 入力なし：中央
2. 予測候補表示：左端
3. 「取り消し」表示：中央左側
となっていた。ボタンの位置がコロコロ変わるとよくないので、3を2に統合し、「取り消し」表示中も左端にタブバーボタンを置くように変更した

fix: タブバーボタンがこれまで3箇所に動いていたのを、2箇所に減らした

---

AzooKeyCore/Sources/AzooKeyUtils/Custard/CustardManager.swift
AzooKeyCore/Sources/SwiftUIUtils/HelpAlertButton.swift
MainApp/Customize/CodableActionDataEditor.swift
MainApp/Customize/CustardInterfaceKeyEditor.swift
MainApp/Customize/EditingScrollCustardView.swift
MainApp/Customize/EditingTenkeyCustardView.swift
MainApp/Setting/BooleanSetting/BoolSettingView.swift
Resources/Localizable.xcstrings

複数のカイゼンを導入
* キーの編集画面でのシートの利用をやめ、キープレビューと編集画面を統合
* いくつかの説明文をはてなマークの中に突っ込んだ
* ラベルの種類を可能な限り「自動」に設定し、編集負荷を軽減
* 見えている必要のないビューをいくつか削除
* 命名を変更
* ナビゲーションタイトルバーを小さめに表示
* キーのタブ同士でのコピペを可能に
* プレビューのボタンをトグル式に変更
* 「文字を入力」アクションのデフォルトを空文字に変更

feat: フリックカスタムタブエディタの改善

---

AzooKeyCore/Sources/KeyboardViews/View/CustomKeybaord/SimpleKeyView/SimpleKeyView.swift
AzooKeyCore/Sources/KeyboardViews/View/FlickKeyboard/KeyView/FlickKeyView.swift
AzooKeyCore/Sources/KeyboardViews/View/QwertyKeyboard/KeyView/QwertyKeyView.swift

#500 のfollow-up。0.1秒だと誤判定が多いようなので、0.125秒に調整

chore: change light longpress duration from 0.1 to 0.125

---

Keyboard/Display/KeyboardViewController.swift

fix #489 
副作用が未知なのでしばらく運用してみる
作文ツール起動中にSiriを起動してタイプ入力しようとするとキーボードが出てこない
* 現在のコードではタイプ入力しようとするとキーボードが2重に出てくるので、どちらがマシかという問題になる

fix: 余計な処理を行わないようにして、ViewControllerをシンプルに

---

AzooKeyCore/Sources/AzooKeyUtils/Custard/CustardManager.swift
MainApp/Customize/CustardInformationView.swift
MainApp/Theme/ThemeShareView.swift
MainApp/azooKey.entitlements
Resources/Localizable.xcstrings

azooKeyではカスタムタブファイルをURLから読み込む機能をサポートしてきたが、URLを作成する機能は持っていなかった。このため、自分でファイルをホストし、提供できる人しか不特定多数にカスタムタブをシェアすることはできなかった。
今回、 custard.azookey.com に新規にサーバを立て、共有用リンクを発行するバックエンドとした。これにより、ユーザは自作したタブに対して共有用リンクを発行し、このリンクを他人に渡すことでシェアできるようになる。
また、Universal Linkにも対応したため、他のアプリで共有されたリンクを開くことで直接azooKeyが開かれ、読み込める。

feat: 共有用リンクを発行する機能を追加

---

AzooKeyCore/Sources/KeyboardViews/ClipboardHistoryManager.swift

- ensure new clipboard history items are added even when only pinned items exist
- `swift test` *(fails: Failed to clone repository https://github.com/azooKey/CustardKit)*

Fix clipboard history insertion bug

---

MainApp/Customize/EditingScrollCustardView.swift
MainApp/Customize/EditingTenkeyCustardView.swift
MainApp/Setting/AdditionalDict/AzooKeyUserDictionary.swift
MainApp/Setting/LearningType/LearningTypeSettingItemView.swift
MainApp/Setting/SettingTab.swift
MainApp/Setting/Template/TemplateEditingView.swift
MainApp/Setting/Template/TemplateListView.swift
MainApp/UpdateInformationView.swift

fix: #518 
- modernize UI code to use `LabeledContent` instead of `HStack`+`Spacer`
- update template, setting and customization views
- apply the same pattern in the update information view
- `swift test` *(fails: Could not find Package.swift)*

refactor: Use LabeledContent for labeled fields

---

.gitignore
AzooKeyCore/Package.swift
AzooKeyCore/Sources/AzooKeyUtils/Custard/CustardManager.swift
AzooKeyCore/Tests/AzooKeyUtilsTests/CustardManagerTests.swift

fix: #443 
- use `TabBarData.default` when tab bar is missing in `addTabBar`
- add `CustardManagerTests` validating automatic creation of tab bar
- extend package manifest with `AzooKeyUtilsTests` target
- remove changelog file per review
- `swift test` *(fails: Failed to clone repository https://github.com/azooKey/CustardKit)*

fix: Add default tabbar fallback when saving custard

---

MainApp/Customize/CustardInformationView.swift
MainApp/Customize/CustomizeTabView.swift
MainApp/Customize/EditingScrollCustardView.swift
MainApp/Customize/EditingTenkeyCustardView.swift
MainApp/Customize/ManageCustardView.swift

- share one NavigationStack in CustomizeTabView
- pass its path binding into ManageCustardView and editing views
- push CustardInformationView onto that path after saving
- update related links and initializers
- `swift test` *(fails: Could not find Package.swift)*

feat: カスタムタブ作成直後にカスタムタブの情報画面に遷移するように変更

---

Keyboard/Display/KeyboardActionManager.swift

`makeChangeKeyboardButtonView`が呼ばれた瞬間にクラッシュしたレポートがこの2週間で複数届いていた。unowned delegateがnilになっていたことによるエラーであるようなので、ひとまずnilの場合は見た目だけのものを返す実装にすることで安全にした。

fix: safer makeChangeKeyboardButtonView impl for avoiding crash

---

MainApp/Customize/CustardInformationView.swift
MainApp/Customize/CustomizeTabView.swift
MainApp/Customize/ManageCustardView.swift
MainApp/MainApp.swift
MainApp/Setting/SettingTab.swift

* 特定端末で（環境依存で）`CustardInformationView`において「編集」を始めたときにクラッシュする問題があった
* 探索の結果、 #564 でこのエラーが入ったことがわかった
* 調査の結果、`MainAppStates`を`@EnvironmentObject`で受けた状態でさらに`@Binding`で`custardManager`を受けたのが原因と推定されたので、これを修正したところ、クラッシュする問題の解消を確認した
* 特にWarning/Errorが出ないので、今後再発しないよう注意が必要

fix: クラッシュする不具合を修正

---

AzooKeyCore/Sources/KeyboardViews/View/KeyboardBar/KeyboardBarView.swift

resolve #575
アイテムが一つもない場合はデフォルトのタブバーを表示するように変更した。

fix: タブバーのアイテムがひとつもない場合、デフォルトのタブバーを表示するように変更

---

AzooKeyCore/Package.swift
AzooKeyCore/Sources/AzooKeyUtils/AzooKeyTheme/ThemeManager.swift

本Pull Requestでは、学習データが本来の仕様である32日間保持されるべきところ、数日単位でリセットされてしまう問題を修正します。調査の結果、「起動直後に何も操作せずにキーボードを閉じる」操作によりリセットが発生することを突き止めました。これは、本来`convertRequestOptions`がDicdataStoreに送信され、その後`LearningManager.save()`が呼ばれるべき処理経路が、「何も操作しない」ケースでは存在せず、デフォルト値で処理されるためにリセットが発生していたことがわかりました。
該当の処理をAZKKC側で修正し、デフォルト値を`nil`にしておくことで不適切なオプションのまま処理が進むことを防止するようにしました。この変更はAZKKCのv0.8.5以降で利用可能なため、この新しい実装を参照するように変更しました。
* https://github.com/azooKey/AzooKeyKanaKanjiConverter/pull/204

fix: 学習が意図せずにリセットされる問題を修正

---

AzooKeyCore/Sources/KeyboardViews/View/KeyboardView.swift

feat: clip shape with rounded corner within iOS 26

---

AzooKeyCore/Sources/KeyboardViews/View/SpecialTabs/ClipboardHistoryTab.swift

右端に「･･･」ボタンを置き、「全て削除」を追加した。このボタンは小さくてかなり押しづらいが、破壊的操作であることを踏まえると押しにくいくらいでちょうど良いと思っている。

feat: クリップボードの履歴タブに全削除ボタンを追加
